version: '3.8'

services:
  frontend:
    container_name: todo-frontend
    build:
      context: ./todo-frontend/
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URL=//localhost:8080/api
    ports:
      - 3000:80
    environment:
      - REACT_APP_BACKEND_URL=//localhost:8080/api
    volumes:
      - ./todo-frontend/nginx.conf:/etc/nginx/nginx.conf:ro

  nginx:
    image: nginx:1.20.1
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    
  api:
    image: todo-backend
    container_name: api
    build: 
      context: ./todo-backend/
      dockerfile: Dockerfile
    ports:
      - 3030:3030
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - PORT=3030
    volumes:
      - ./todo-backend:/usr/src/app
  
  mongo:
    image: mongo
    container_name: database
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db
  
  redis:
    container_name: cache
    image: redis
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./todo-backend:/redis_data:/data

volumes:
  mongo_data: